### ISSUE TITLE
got a packet bigger than 'max_allowed_packet'

### ISSUE THREAD

**Issue by book000** [book000/twitterts#1301]

**Comment by book000** [comment]
https://stackoverflow.com/questions/39369367/increase-max-allowed-packet-size-in-mysql-docker

mariadbでも同じ。
https://mariadb.com/docs/server/ref/mdb/system-variables/max_allowed_packet/

```
version: "3"
services:
  data:
    image: "mysql:5.7.20"
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
```
